HOTFIX: Removed leftover playerDestroyedFlags reference
Error: Cannot set properties of undefined (setting '3')
Line 719 was trying to set this.playerDestroyedFlags[playerIndex] = 1
but the array was removed in previous commit

Fixed by removing the line - no longer needed with new clean approach

v=190